/**************************************************************************************************\
 *** 
 *** Simulink model       : VcAesAir_OPortMvd
 *** TargetLink subsystem : VcAesAir_OPortMvd/VcAesAir
 *** Codefile             : Tab1DIntpI1T0.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2019-02-05 11:36:51
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : enabled
 *** Generate 64bit functions                 : disabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\TL4_3\dSPACE TargetLink 4.3\Matlab\Tl\Config\code
 ***                                            gen\cconfig.xml
 *** Root style sheet                         : C:\TL4_3\dSPACE TargetLink 4.3\Matlab\Tl\XML\CodeGen
 ***                                            \Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS         CORRESPONDING SIMULINK SUBSYSTEM
 *** SAesAir1       VcAesAir
 *** SAesAir2       VcAesAir/VcAesAir
 *** SAesAir3       VcAesAir/VcAesAir/1_AirTarDyn
 *** SAesAir4       VcAesAir/VcAesAir/2_ThrCtrl
 *** SAesAir5       VcAesAir/VcAesAir/3_AirCdn
 *** SAesAir6       VcAesAir/VcAesAir/VccDocBlock
 *** SAesAir7       VcAesAir/VcAesAir/1_AirTarDyn/11_CylTarStrt
 *** SAesAir8       VcAesAir/VcAesAir/1_AirTarDyn/12_AirTarMin
 *** SAesAir9       VcAesAir/VcAesAir/1_AirTarDyn/13_AirTarMinSurge
 *** SAesAir10      VcAesAir/VcAesAir/1_AirTarDyn/14_AirTarFil
 *** SAesAir11      VcAesAir/VcAesAir/1_AirTarDyn/15_TcRgnDsl
 *** SAesAir12      VcAesAir/VcAesAir/1_AirTarDyn/16_PreLookUp
 *** SAesAir13      VcAesAir/VcAesAir/1_AirTarDyn/17_AirTarIni
 *** SAesAir14      VcAesAir/VcAesAir/1_AirTarDyn/PreprocessorName
 *** SAesAir15      VcAesAir/VcAesAir/1_AirTarDyn/PreprocessorName1
 *** SAesAir16      VcAesAir/VcAesAir/1_AirTarDyn/VccDocBlock
 *** SAesAir17      VcAesAir/VcAesAir/1_AirTarDyn/11_CylTarStrt/VccDocBlock
 *** SAesAir18      VcAesAir/VcAesAir/1_AirTarDyn/11_CylTarStrt/VccDocBlock/EmptySubsystem
 *** SAesAir19      VcAesAir/VcAesAir/1_AirTarDyn/12_AirTarMin/121_AirTarBoost
 *** SAesAir20      VcAesAir/VcAesAir/1_AirTarDyn/12_AirTarMin/122_AirCnvnFil
 *** SAesAir21      VcAesAir/VcAesAir/1_AirTarDyn/12_AirTarMin/VccDocBlock
 *** SAesAir22      VcAesAir/VcAesAir/1_AirTarDyn/12_AirTarMin/121_AirTarBoost/FirstOrderFilterMem
 *** SAesAir23      VcAesAir/VcAesAir/1_AirTarDyn/12_AirTarMin/121_AirTarBoost/VccDocBlock
 *** SAesAir24      VcAesAir/VcAesAir/1_AirTarDyn/12_AirTarMin/121_AirTarBoost/VccDocBlock/EmptySubs
 ***                ystem
 *** SAesAir25      VcAesAir/VcAesAir/1_AirTarDyn/12_AirTarMin/122_AirCnvnFil/FirstOrderFilterMem
 *** SAesAir26      VcAesAir/VcAesAir/1_AirTarDyn/12_AirTarMin/122_AirCnvnFil/VccDocBlock
 *** SAesAir27      VcAesAir/VcAesAir/1_AirTarDyn/12_AirTarMin/122_AirCnvnFil/VccDocBlock/EmptySubsy
 ***                stem
 *** SAesAir28      VcAesAir/VcAesAir/1_AirTarDyn/12_AirTarMin/VccDocBlock/EmptySubsystem
 *** SAesAir29      VcAesAir/VcAesAir/1_AirTarDyn/13_AirTarMinSurge/131_AirTarMinSurgeFct
 *** SAesAir30      VcAesAir/VcAesAir/1_AirTarDyn/13_AirTarMinSurge/PreprocessorName
 *** SAesAir31      VcAesAir/VcAesAir/1_AirTarDyn/13_AirTarMinSurge/PreprocessorName1
 *** SAesAir32      VcAesAir/VcAesAir/1_AirTarDyn/13_AirTarMinSurge/VccDocBlock
 *** SAesAir33      VcAesAir/VcAesAir/1_AirTarDyn/13_AirTarMinSurge/131_AirTarMinSurgeFct/VccDocBloc
 ***                k
 *** SAesAir34      VcAesAir/VcAesAir/1_AirTarDyn/13_AirTarMinSurge/131_AirTarMinSurgeFct/md_AirTarM
 ***                inSurgeNom
 *** SAesAir35      VcAesAir/VcAesAir/1_AirTarDyn/13_AirTarMinSurge/131_AirTarMinSurgeFct/VccDocBloc
 ***                k/EmptySubsystem
 *** SAesAir36      VcAesAir/VcAesAir/1_AirTarDyn/13_AirTarMinSurge/VccDocBlock/EmptySubsystem
 *** SAesAir37      VcAesAir/VcAesAir/1_AirTarDyn/14_AirTarFil/FirstOrderFilterMem1
 *** SAesAir38      VcAesAir/VcAesAir/1_AirTarDyn/14_AirTarFil/VccDocBlock
 *** SAesAir39      VcAesAir/VcAesAir/1_AirTarDyn/14_AirTarFil/VccDocBlock/EmptySubsystem
 *** SAesAir40      VcAesAir/VcAesAir/1_AirTarDyn/15_TcRgnDsl/VccDocBlock
 *** SAesAir41      VcAesAir/VcAesAir/1_AirTarDyn/15_TcRgnDsl/VccDocBlock/EmptySubsystem
 *** SAesAir42      VcAesAir/VcAesAir/1_AirTarDyn/16_PreLookUp/VccDocBlock
 *** SAesAir43      VcAesAir/VcAesAir/1_AirTarDyn/16_PreLookUp/VccDocBlock/EmptySubsystem
 *** SAesAir44      VcAesAir/VcAesAir/1_AirTarDyn/VccDocBlock/EmptySubsystem
 *** SAesAir45      VcAesAir/VcAesAir/2_ThrCtrl/21_Imc
 *** SAesAir46      VcAesAir/VcAesAir/2_ThrCtrl/22_IntkMnfldDyn
 *** SAesAir47      VcAesAir/VcAesAir/2_ThrCtrl/23_DParts
 *** SAesAir48      VcAesAir/VcAesAir/2_ThrCtrl/24_ThrWotCtrl
 *** SAesAir49      VcAesAir/VcAesAir/2_ThrCtrl/25_CtrlMax
 *** SAesAir50      VcAesAir/VcAesAir/2_ThrCtrl/Saturation1
 *** SAesAir51      VcAesAir/VcAesAir/2_ThrCtrl/VccDocBlock
 *** SAesAir52      VcAesAir/VcAesAir/2_ThrCtrl/Z_ThrCtrlTcGain
 *** SAesAir53      VcAesAir/VcAesAir/2_ThrCtrl/fac_ThrCtrlPCmp
 *** SAesAir54      VcAesAir/VcAesAir/2_ThrCtrl/21_Imc/211_Hold
 *** SAesAir55      VcAesAir/VcAesAir/2_ThrCtrl/21_Imc/FirstOrderFilter1
 *** SAesAir56      VcAesAir/VcAesAir/2_ThrCtrl/21_Imc/Saturation2
 *** SAesAir57      VcAesAir/VcAesAir/2_ThrCtrl/21_Imc/VccDocBlock
 *** SAesAir58      VcAesAir/VcAesAir/2_ThrCtrl/21_Imc/tc_ImcCorrnCyl
 *** SAesAir59      VcAesAir/VcAesAir/2_ThrCtrl/21_Imc/VccDocBlock/EmptySubsystem
 *** SAesAir60      VcAesAir/VcAesAir/2_ThrCtrl/22_IntkMnfldDyn/VccDocBlock
 *** SAesAir61      VcAesAir/VcAesAir/2_ThrCtrl/22_IntkMnfldDyn/VccDocBlock/EmptySubsystem
 *** SAesAir62      VcAesAir/VcAesAir/2_ThrCtrl/23_DParts/FirstOrderFilter
 *** SAesAir63      VcAesAir/VcAesAir/2_ThrCtrl/23_DParts/FirstOrderFilter1
 *** SAesAir64      VcAesAir/VcAesAir/2_ThrCtrl/23_DParts/VccDocBlock
 *** SAesAir65      VcAesAir/VcAesAir/2_ThrCtrl/23_DParts/Z_ThrCtrlDEst
 *** SAesAir66      VcAesAir/VcAesAir/2_ThrCtrl/23_DParts/Z_ThrCtrlDGain
 *** SAesAir67      VcAesAir/VcAesAir/2_ThrCtrl/23_DParts/Z_ThrCtrlDTar
 *** SAesAir68      VcAesAir/VcAesAir/2_ThrCtrl/23_DParts/VccDocBlock/EmptySubsystem
 *** SAesAir69      VcAesAir/VcAesAir/2_ThrCtrl/24_ThrWotCtrl/VccDocBlock
 *** SAesAir70      VcAesAir/VcAesAir/2_ThrCtrl/24_ThrWotCtrl/m_ThrWotCtrlThd
 *** SAesAir71      VcAesAir/VcAesAir/2_ThrCtrl/24_ThrWotCtrl/VccDocBlock/EmptySubsystem
 *** SAesAir72      VcAesAir/VcAesAir/2_ThrCtrl/25_CtrlMax/VccDocBlock
 *** SAesAir73      VcAesAir/VcAesAir/2_ThrCtrl/25_CtrlMax/fac_ThrCtrlMaxCorrn
 *** SAesAir74      VcAesAir/VcAesAir/2_ThrCtrl/25_CtrlMax/VccDocBlock/EmptySubsystem
 *** SAesAir75      VcAesAir/VcAesAir/2_ThrCtrl/VccDocBlock/EmptySubsystem
 *** SAesAir76      VcAesAir/VcAesAir/3_AirCdn/SignalDelay
 *** SAesAir77      VcAesAir/VcAesAir/VccDocBlock/EmptySubsystem
 *** 
 *** SUBSYS         CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE        CORRESPONDING STATEFLOW NODE                    DESCRIPTION
 *** 
 *** TargetLink version      : 4.3p2 from 20-Sep-2018
 *** Code generator version  : Build Id 4.3.0.27 from 2018-09-24 17:55:03
\**************************************************************************************************/

#ifndef TAB1DINTPI1T0_C
#define TAB1DINTPI1T0_C

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "Tab1DIntpI1T0.h"

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Tab1DIntpI1T0
 *** 
 ***  DESCRIPTION:
 ***      Automatic generated function for Interpolation using PreLook-Up blocks.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const UInt8 *      z_table             pointer to table vector
 ***      UInt8              irx[2]              1. table input index
 ***
 ***  RETURNS:
 ***      UInt8
 ***
 ***  SETTINGS:
 ***      Number of table dimensions.........: 1
 ***      Interpolation......................: on
 ***      Distances fit into given bitlengths: no
 ***
\**************************************************************************************************/
#include "CVC_CODE_START.h"
UInt8 Tab1DIntpI1T0(const UInt8 * z_table, UInt8 irx[2])
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   UInt8 Aux_U8;
   UInt8 Aux_U8_a;

   z_table += irx[0];
   Aux_U8 = *(z_table++);
   if (irx[1] != 0) {
      Aux_U8_a = *z_table;
      if (Aux_U8 <= Aux_U8_a) {
         Aux_U8 += ((UInt8) (((UInt16) (((UInt16) (UInt8) (Aux_U8_a - Aux_U8)) * ((UInt16) irx[1])))
           >> 8));
      }
      else {
         Aux_U8 -= ((UInt8) (((UInt16) (((UInt16) (UInt8) (Aux_U8 - Aux_U8_a)) * ((UInt16) irx[1])))
           >> 8));
      }
   }
   return Aux_U8;
}
#include "CVC_CODE_END.h"

/*------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/
#endif /* TAB1DINTPI1T0_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
