---
- name: Run Blackduck
  ansible.builtin.shell: >
    bash detect8.sh
    --detect.project.name={{ blackduck_project_name }}
    --detect.project.version.name={{ blackduck_package_version }}
    --blackduck.url={{ blackduck_url }}
    --blackduck.api.token=$BLACKDUCK_TOKEN
    --detect.blackduck.scan.mode={{ blackduck_scan_mode }}
    {{ blackduck_additional_arguments }} > blackduck_output.txt
  args:
    chdir: "{{ blackduck_workspace }}"
  environment:
    BLACKDUCK_TOKEN: "{{ blackduck_secret.token }}"
  register: blackduck_result
  no_log: true
  ignore_errors: true

- name: Print Blackduck log
  ansible.builtin.command: cat blackduck_output.txt
  args:
    chdir: "{{ blackduck_workspace }}"
  register: blackduck_log

- name: Extract version using regex
  set_fact:
    blackduck_report_version: "{{ (blackduck_log | regex_search('versions/([^/]+)/components', '\\1'))[0] }}"

- name: Debug version
  debug:
    var: blackduck_report_version

- name: Fail if Black Duck return non 0 rc
  fail:
    msg: Failed job in gate

# Here is fetching the notice file, comparing it with the previous one, and updating it if there are new licenses

# linking artifacts to return to zuul web
