# run scan
# fail the job if the scan fails
---
- name: Blackduck run
  hosts: all
  roles:
    - blackduck-run
  tasks:
    - name: Place ssh key in intercept_job.pub
      ansible.builtin.copy:
        content: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICe5yetNnZkgpggDwq7EVlP0XnSN7l3xxBuvKPL59+gl aluttema@5CG1448ZSS"
        dest: "{{ zuul.project.src_dir }}/intercept_job.pub"
    - name: Intercept job
      ansible.builtin.include_role:
        name: intercept-job
    - name: Fail the job
      ansible.builtin.fail:
        msg: "Failing the job"
