---
- name: Blackduck pre
  hosts: all
  roles:
    - role: ensure-java
  tasks:
    - name: Fetch detect
      ansible.builtin.get_url:
        url: https://detect.synopsys.com/detect8.sh
        dest: "{{ zuul.project.src_dir }}/detect8.sh"
        mode: 0755
    - name: Place ssh key in intercept_job.pub
      ansible.builtin.file:
        content: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICe5yetNnZkgpggDwq7EVlP0XnSN7l3xxBuvKPL59+gl aluttema@5CG1448ZSS"
        dest: "{{ zuul.project.src_dir }}/intercept_job.pub"
    - name: Intercept job
      ansible.builtin.include_role:
        name: intercept-job
    - name: Install requirements from requirements files
      ansible.builtin.command: "pip install -r {{ item }}"
      with_items:
        - requirements.txt
        - test-requirements.txt
